### ISSUE TITLE
Cannot access ambient const enums when the '--isolatedModules' flag is provided.ts(2748)

### ISSUE THREAD

**Issue by rv-jbaker** [sambrmg/mysql-error-codes#1]
Hi Sambrmg,

thanks for this package makes things easy however I am getting this error from typescript:

> Cannot access ambient const enums when the '--isolatedModules' flag is provided.ts(2748)

I think it can be resolved by updating your index.d.ts file to use `declare` instead of `const`. I only say that because looking at the [http-status-codes|https://github.com/prettymuchbryce/http-status-codes] built package their file uses `declare` instead of `const` and they don't get this error.

Thanks and hope this helps 👍

**Comment by guilhermehmcruz** [comment]
Hi Joseph Baker,

Thanks for reporting this problem, I solved it with `declare` as you proposed, the version is the 0.1.3.
